source 'https://rubygems.org'

gem 'cocoon'
gem 'coffee-rails', '~> 4.0.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'less-rails'
gem 'rails', '4.1.6'
gem 'sass-rails', '~> 4.0.3'
gem 'spring',        group: :development
gem 'sqlite3'
gem 'therubyracer'
gem 'turbolinks'
gem 'twitter-bootstrap-rails', git: 'git://github.com/seyhunak/twitter-bootstrap-rails.git', branch: 'bootstrap3'
gem 'uglifier', '>= 1.3.0'
